// ---------------------------------------------------------------------------
// comment_service.dart
// ---------------------------------------------------------------------------
// Firebase integration layer for movie comments (reviews).
//
// Design decisions:
//   • Subcollection `movies/{movieId}/comments` — co-locates comments with
//     the movie, enabling efficient single-query reads without composite
//     indexes.
//   • Streams for comment lists — enables real-time UI updates via
//     StreamBuilder without manual refresh logic.
//   • Server timestamps — guarantees consistent ordering regardless of
//     client clock drift.
//   • Author info denormalized at write time — avoids an extra read per
//     comment to resolve user names.
// ---------------------------------------------------------------------------

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

import '../models/comment.dart';

class CommentService {
  // ── Dependencies ──────────────────────────────────────────────────────────

  final FirebaseFirestore _firestore;
  final FirebaseAuth _auth;

  /// Injectable for testing; defaults to live Firebase instances.
  CommentService({
    FirebaseFirestore? firestore,
    FirebaseAuth? auth,
  })  : _firestore = firestore ?? FirebaseFirestore.instance,
        _auth = auth ?? FirebaseAuth.instance;

  // ── Helpers ───────────────────────────────────────────────────────────────

  /// Returns a reference to the comments subcollection for a given movie.
  CollectionReference _commentsRef(int movieId) =>
      _firestore.collection('movies').doc(movieId.toString()).collection('comments');

  // ── Public API ────────────────────────────────────────────────────────────

  /// Adds a new comment to the given movie.
  ///
  /// Automatically populates `userId`, `userName`, and the user's current
  /// rating (if any) for the movie. Throws [StateError] if no user is signed in.
  ///
  /// Returns the newly created [Comment]'s document ID.
  Future<String> addComment({
    required int movieId,
    required String text,
  }) async {
    final user = _auth.currentUser;
    if (user == null) {
      throw StateError('You must be signed in to post a comment.');
    }

    final trimmed = text.trim();
    if (trimmed.isEmpty) {
      throw ArgumentError('Comment text cannot be empty.');
    }

    // Fetch the user's current rating for this movie, if any.
    double? userRating;
    try {
      final ratingDoc = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('rated_movies')
          .doc(movieId.toString())
          .get();
      
      if (ratingDoc.exists) {
        userRating = (ratingDoc.data()?['rating'] as num?)?.toDouble();
      }
    } catch (_) {
      // Ignore errors fetching rating, comment can proceed without it
    }

    final comment = Comment(
      id: '', // will be auto-generated by Firestore
      movieId: movieId,
      userId: user.uid,
      userName: user.displayName ?? 'Cinephile',
      text: trimmed,
      rating: userRating,
      createdAt: DateTime.now(), // placeholder; server timestamp used in toMap()
    );

    final docRef = await _commentsRef(movieId).add(comment.toMap());
    return docRef.id;
  }

  /// Returns a real-time stream of comments for the given movie, ordered
  /// by creation time (newest first).
  ///
  /// The stream emits a new `List<Comment>` whenever any comment is added,
  /// modified, or deleted.
  Stream<List<Comment>> commentsStream(int movieId) {
    return _commentsRef(movieId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => Comment.fromFirestore(doc))
            .toList());
  }

  /// Deletes a comment by its document ID.
  ///
  /// Only the comment author should call this. Firestore security rules
  /// should enforce `request.auth.uid == resource.data.userId`.
  Future<void> deleteComment({
    required int movieId,
    required String commentId,
  }) async {
    await _commentsRef(movieId).doc(commentId).delete();
  }
}
