// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmBli1qxdsIAV7afdEGz1u-aYbW_W5GBA',
    appId: '1:546844278034:web:066a516391673afd1647cb',
    messagingSenderId: '546844278034',
    projectId: 'movie-tracker-app-954ae',
    authDomain: 'movie-tracker-app-954ae.firebaseapp.com',
    storageBucket: 'movie-tracker-app-954ae.firebasestorage.app',
    measurementId: 'G-26C1EH63DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0JgaAz8APTGVqekv_CnxwJLiVGkfxHiw',
    appId: '1:546844278034:android:679a29b45fc8d8721647cb',
    messagingSenderId: '546844278034',
    projectId: 'movie-tracker-app-954ae',
    storageBucket: 'movie-tracker-app-954ae.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAoHCqQgdf6EGfzsJ-f1HCAWT3M8mCkzA',
    appId: '1:546844278034:ios:7c80c9221d1651641647cb',
    messagingSenderId: '546844278034',
    projectId: 'movie-tracker-app-954ae',
    storageBucket: 'movie-tracker-app-954ae.firebasestorage.app',
    iosBundleId: 'com.example.filmUygulamasi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAoHCqQgdf6EGfzsJ-f1HCAWT3M8mCkzA',
    appId: '1:546844278034:ios:7c80c9221d1651641647cb',
    messagingSenderId: '546844278034',
    projectId: 'movie-tracker-app-954ae',
    storageBucket: 'movie-tracker-app-954ae.firebasestorage.app',
    iosBundleId: 'com.example.filmUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmBli1qxdsIAV7afdEGz1u-aYbW_W5GBA',
    appId: '1:546844278034:web:5eb8692dae55d63f1647cb',
    messagingSenderId: '546844278034',
    projectId: 'movie-tracker-app-954ae',
    authDomain: 'movie-tracker-app-954ae.firebaseapp.com',
    storageBucket: 'movie-tracker-app-954ae.firebasestorage.app',
    measurementId: 'G-B1BVG204NL',
  );
}
